table Amazon
	lineageTag: 9114103a-7943-4f1b-bbfa-832ac17ee67f

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: de28f18b-840a-4dd0-8bfa-5e3ea8320c97
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: a64a008b-9d44-4e96-822f-2c68cca2c0cb
			defaultHierarchy: LocalDateTable_b9e61d49-8ed6-4c3f-832d-b6af01725148.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: b39f255b-5ad6-4fc1-9720-5090f4a15e01
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: b73cda02-8c94-42f1-8103-5fac2484ad5c
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: 5070de04-f118-450d-b47d-c5658123723a
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: b0f091da-9023-4b6d-9b3e-c4acab5cf16c
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adj Close'
		dataType: double
		lineageTag: 7b1e5ff2-2811-4f68-baec-7469bc72f031
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: a23dcf11-afe6-4e9f-a129-3e934770ab24
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition Amazon = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\503ST\OneDrive\Documents\CV\Portfolio\Git Testing\PBI\Amazon.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Adj Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

